name: sjtz-sign-in
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
  # 2024年9月29日注释
    # - cron: "00 23 * * *"
    # - cron: "10 4 * * *"
    # - cron: "55 5 * * *"
    # - cron: "40 10 * * *"
    - cron: "00 23 * * *"
    - cron: "10 4 * * *"
    - cron: "28 6 * * *"
    - cron: "40 10 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: working
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python3 ./main.py
