name: sjtz-sign-in
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "55 23 * * *"
    - cron: "10 4 * * *"
    - cron: "55 5 * * *"
    - cron: "10 10 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: checkIn
        run: python3 ./autoSignIn.py --username chaizhiyang
